name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y jq texlive-fonts-recommended  texlive-latex-recommended
      - run: pdflatex resume.tex
      - name: upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
